name: Rust build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  minimal-setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --no-fail-fast
    - name: Run benchmark test
      # Run the msm benchmark, just to ensure it isn't broken.
      run: cargo bench --bench msm -- --quick

  no-std-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Check no_std compilation
      run: |
        echo "Checking no_std compilation..."
        cargo check --no-default-features --verbose
    - name: Check std compilation
      run: |
        echo "Checking std compilation..."
        cargo check --verbose
    - name: Check all features
      run: |
        echo "Checking with all features..."
        cargo check --all-features --verbose


  full-setup:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [nightly]

    steps:
    - uses: actions/checkout@v6
    - run: rustup update ${{ matrix.toolchain }}
    - name: Build (nightly)
      run: cargo +${{ matrix.toolchain }} build --all-features --verbose
    - name: Build no_std (nightly)
      run: cargo +${{ matrix.toolchain }} build --no-default-features --verbose
    - name: Run tests (nightly)
      run: cargo +${{ matrix.toolchain }} test --all-features --verbose --no-fail-fast

  wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup `wasmtime`
      uses: bytecodealliance/actions/wasmtime/setup@v1
    - name: Build
      run: cargo build --target wasm32-wasip1 --verbose
    - name: Run tests
      run: cargo test --target wasm32-wasip1 --verbose --no-fail-fast
    - name: Run benchmark test
      # Run the msm benchmark, just to ensure it isn't broken.
      run: cargo bench --target wasm32-wasip1 --bench msm -- --quick
